name: Continuous Integration (CI)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Automated Tests
    runs-on: ubuntu-latest 

    steps:
      # 1. pull GitHub code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. configure local Python 3.11 enviroment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. add dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. execute automation test tools
      - name: Execute Pytest Suite
        run: |
          python -m pytest -v